/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// information about the ip's custom dns, if it has been configured
type IpslistCustomDns struct {
	// a boolean indicating whether custom dns has been configured for this ip
	Enabled bool `json:"enabled,omitempty"`
	// whether the ip's custom dns is currently valid
	Valid bool `json:"valid,omitempty"`
	// if the ip's custom dns is invalid, this will include details about the error
	Error_ string `json:"error,omitempty"`
}
