/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

type MetadataAddBody struct {
	// a valid api key
	Key string `json:"key"`
	// a unique identifier for the metadata field
	Name string `json:"name"`
	// Mustache template to control how the metadata is rendered in your activity log
	ViewTemplate string `json:"view_template,omitempty"`
}
