/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// information on an individual open
type MessagessearchOpensDetail struct {
	// the unix timestamp from when the message was opened
	Ts int32 `json:"ts,omitempty"`
	// the IP address that generated the open
	Ip string `json:"ip,omitempty"`
	// the approximate region and country that the opening IP is located
	Location string `json:"location,omitempty"`
	// the email client or browser data of the open
	Ua string `json:"ua,omitempty"`
}
