/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

type Body41 struct {
	// a valid api key
	Key string `json:"key"`
	// a scheduled email id, as returned by any of the messages/send calls or messages/list-scheduled
	Id string `json:"id"`
	// the new UTC timestamp when the message should sent. Mandrill can't time travel, so if you specify a time in past the message will be sent immediately
	SendAt time.Time `json:"send_at"`
}
