/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

type TemplatesListBody struct {
	// a valid api key
	Key string `json:"key"`
	// an optional label to filter the templates
	Label string `json:"label,omitempty"`
}
