/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// information about a specific smtp event
type InlineResponse20032SmtpEvents struct {
	// the Unix timestamp when the event occured
	Ts int32 `json:"ts,omitempty"`
	// the message's state as a result of this event
	Type_ string `json:"type,omitempty"`
	// the SMTP response from the recipient's server
	Diag string `json:"diag,omitempty"`
}
