/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// an aggregate summary of the tag's sending stats
type InlineResponse20059Stats struct {
	Today *InlineResponse20059StatsToday `json:"today,omitempty"`
	Last7Days *InlineResponse20059StatsLast7Days `json:"last_7_days,omitempty"`
	Last30Days *InlineResponse20059StatsLast30Days `json:"last_30_days,omitempty"`
	Last60Days *InlineResponse20059StatsLast60Days `json:"last_60_days,omitempty"`
	Last90Days *InlineResponse20059StatsLast90Days `json:"last_90_days,omitempty"`
}
