/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body70 struct {
	// a valid api key
	Key string `json:"key"`
	// the immutable name of an existing template
	Name string `json:"name"`
	// the new default sending address
	FromEmail string `json:"from_email,omitempty"`
	// the new default from name
	FromName string `json:"from_name,omitempty"`
	// the new default subject line
	Subject string `json:"subject,omitempty"`
	// the new code for the template
	Code string `json:"code,omitempty"`
	// the new default text part to be used
	Text string `json:"text,omitempty"`
	// set to false to update the draft version of the template without publishing
	Publish bool `json:"publish,omitempty"`
	// an optional array of up to 10 labels to use for filtering templates
	Labels []string `json:"labels,omitempty"`
}
