/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// information about the status of the pool that was deleted
type InlineResponse20025 struct {
	// the name of the pool
	Pool string `json:"pool,omitempty"`
	// whether the pool was deleted
	Deleted bool `json:"deleted,omitempty"`
}
