/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// a status object containing the address and whether the deletion succeeded
type InlineResponse2002 struct {
	// the email address that was removed from the denylist
	Email string `json:"email,omitempty"`
	// whether the address was deleted successfully
	Deleted bool `json:"deleted,omitempty"`
}
