/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// an aggregate summary of the account's sending stats
type InlineResponse20072Stats struct {
	Today *InlineResponse20072StatsToday `json:"today,omitempty"`
	Last7Days *InlineResponse20072StatsLast7Days `json:"last_7_days,omitempty"`
	Last30Days *InlineResponse20072StatsLast30Days `json:"last_30_days,omitempty"`
	Last60Days *InlineResponse20072StatsLast60Days `json:"last_60_days,omitempty"`
	Last90Days *InlineResponse20072StatsLast90Days `json:"last_90_days,omitempty"`
	AllTime *InlineResponse20072StatsAllTime `json:"all_time,omitempty"`
}
