/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body23 struct {
	// a valid api key
	Key string `json:"key"`
	// a dedicated ip address
	Ip string `json:"ip"`
	// the name of the new pool to add the dedicated ip to
	Pool string `json:"pool"`
	// whether to create the pool if it does not exist; if false and the pool does not exist, an Unknown_Pool will be thrown.
	CreatePool bool `json:"create_pool,omitempty"`
}
