/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body20 struct {
	// a valid api key
	Key string `json:"key"`
	// whether to enable warmup mode for the ip
	Warmup bool `json:"warmup,omitempty"`
	// the id of the pool to add the dedicated ip to, or null to use your account's default pool
	Pool string `json:"pool,omitempty"`
}
