/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// the information for a single matching message
type InlineResponse20030 struct {
	// the Unix timestamp from when this message was sent
	Ts int32 `json:"ts,omitempty"`
	// the message's unique id
	Id string `json:"_id,omitempty"`
	// the email address of the sender
	Sender string `json:"sender,omitempty"`
	// the unique name of the template used, if any
	Template string `json:"template,omitempty"`
	// the message's subject line
	Subject string `json:"subject,omitempty"`
	// the recipient email address
	Email string `json:"email,omitempty"`
	// list of tags on this message
	Tags []string `json:"tags,omitempty"`
	// how many times has this message been opened
	Opens int32 `json:"opens,omitempty"`
	// list of individual opens for the message
	OpensDetail []MessagessearchOpensDetail `json:"opens_detail,omitempty"`
	// how many times has a link been clicked in this message
	Clicks int32 `json:"clicks,omitempty"`
	// list of individual clicks for the message
	ClicksDetail []MessagessearchClicksDetail `json:"clicks_detail,omitempty"`
	// sending status of this message
	State string `json:"state,omitempty"`
	// any custom metadata provided when the message was sent
	Metadata *interface{} `json:"metadata,omitempty"`
}
