/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// details about the domain's DKIM record
type SendersdomainsDkim struct {
	// whether the domain's DKIM record is valid for use with Mandrill
	Valid bool `json:"valid,omitempty"`
	// when the domain's DKIM record will be considered valid for use with Mandrill as a UTC string in YYYY-MM-DD HH:MM:SS format. If set, this indicates that the record is valid now, but was previously invalid, and Mandrill will wait until the record's TTL elapses to start using it.
	ValidAfter time.Time `json:"valid_after,omitempty"`
	// an error describing the DKIM record, or null if the record is correct
	Error_ string `json:"error,omitempty"`
}
