/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body struct {
	// a valid api key
	Key string `json:"key"`
	// an email address to add to the allowlist
	Email string `json:"email"`
	// an optional description of why the email was added to the allowlist
	Comment string `json:"comment,omitempty"`
}
