/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// a scheduled email
type InlineResponse20035 struct {
	// the scheduled message id
	Id string `json:"_id,omitempty"`
	// the UTC timestamp when the message was created, in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the UTC timestamp when the message will be sent, in YYYY-MM-DD HH:MM:SS format
	SendAt time.Time `json:"send_at,omitempty"`
	// the email's sender address
	FromEmail string `json:"from_email,omitempty"`
	// the email's recipient
	To string `json:"to,omitempty"`
	// the email's subject
	Subject string `json:"subject,omitempty"`
}
