/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the result of rendering the given template with the content and merge field values injected
type InlineResponse20066 struct {
	// the rendered HTML as a string
	Html string `json:"html,omitempty"`
}
