/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// information about an individual attachment
type InlineResponse20034Attachments struct {
	// the file name of the attachment
	Name string `json:"name,omitempty"`
	// the MIME type of the attachment
	Type_ string `json:"type,omitempty"`
	// if this is set to true, the attachment is not pure-text, and the content will be base64 encoded
	Binary bool `json:"binary,omitempty"`
	// the content of the attachment as a base64 encoded string
	Content string `json:"content,omitempty"`
}
