/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the individual URL stats
type InlineResponse20067 struct {
	// the URL to be tracked
	Url string `json:"url,omitempty"`
	// the number of emails that contained the URL
	Sent int32 `json:"sent,omitempty"`
	// the number of times the URL has been clicked from a tracked email
	Clicks int32 `json:"clicks,omitempty"`
	// the number of unique emails that have generated clicks for this URL
	UniqueClicks int32 `json:"unique_clicks,omitempty"`
}
