/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// the information for a single hour
type InlineResponse20069 struct {
	// the hour as a UTC date string in YYYY-MM-DD HH:MM:SS format
	Time time.Time `json:"time,omitempty"`
	// the number of emails that were sent with the URL during the hour
	Sent int32 `json:"sent,omitempty"`
	// the number of times the URL was clicked during the hour
	Clicks int32 `json:"clicks,omitempty"`
	// the number of unique clicks generated for emails sent with this URL during the hour
	UniqueClicks int32 `json:"unique_clicks,omitempty"`
}
