/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the tag that was deleted
type InlineResponse20058 struct {
	// the actual tag as a string
	Tag string `json:"tag,omitempty"`
	// the tag's current reputation on a scale from 0 to 100.
	Reputation int32 `json:"reputation,omitempty"`
	// the total number of messages sent with this tag
	Sent int32 `json:"sent,omitempty"`
	// the total number of hard bounces by messages with this tag
	HardBounces int32 `json:"hard_bounces,omitempty"`
	// the total number of soft bounces by messages with this tag
	SoftBounces int32 `json:"soft_bounces,omitempty"`
	// the total number of rejected messages with this tag
	Rejects int32 `json:"rejects,omitempty"`
	// the total number of spam complaints received for messages with this tag
	Complaints int32 `json:"complaints,omitempty"`
	// the total number of unsubscribe requests received for messages with this tag
	Unsubs int32 `json:"unsubs,omitempty"`
	// the total number of times messages with this tag have been opened
	Opens int32 `json:"opens,omitempty"`
	// the total number of times tracked URLs in messages with this tag have been clicked
	Clicks int32 `json:"clicks,omitempty"`
	// the number of unique opens for emails sent with this tag
	UniqueOpens int32 `json:"unique_opens,omitempty"`
	// the number of unique clicks for emails sent with this tag
	UniqueClicks int32 `json:"unique_clicks,omitempty"`
}
