/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// information about an individual image
type InlineResponse20034Images struct {
	// the Content-ID of the embedded image
	Name string `json:"name,omitempty"`
	// the MIME type of the image
	Type_ string `json:"type,omitempty"`
	// the content of the image as a base64 encoded string
	Content string `json:"content,omitempty"`
}
