/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// Information about the dedicated ip pool
type InlineResponse20024 struct {
	// this pool's name
	Name string `json:"name,omitempty"`
	// the date and time that this pool was created as a UTC timestamp in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the dedicated IPs in this pool
	Ips []IpslistpoolsIps `json:"ips,omitempty"`
}
