/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// information about the verification that was sent
type InlineResponse20047 struct {
	// \"sent\" indicates that the verification has been sent, \"already_verified\" indicates that the domain has already been verified with your account
	Status string `json:"status,omitempty"`
	// the domain name you provided
	Domain string `json:"domain,omitempty"`
	// the email address the verification email was sent to
	Email string `json:"email,omitempty"`
}
