/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// the information for each allowlist entry
type InlineResponse2001 struct {
	// the email that is allowlisted
	Email string `json:"email,omitempty"`
	// a description of why the email was allowlisted
	Detail string `json:"detail,omitempty"`
	// when the email was added to the allowlist
	CreatedAt time.Time `json:"created_at,omitempty"`
}
