/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body47 struct {
	// a valid api key
	Key string `json:"key"`
	// an optional email address to search by
	Email string `json:"email,omitempty"`
	// whether to include rejections that have already expired.
	IncludeExpired bool `json:"include_expired,omitempty"`
	// an optional unique identifier for the subaccount to limit the denylist
	Subaccount string `json:"subaccount,omitempty"`
}
