/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// the detailed information on the tag
type InlineResponse20059 struct {
	// the actual tag as a string
	Tag string `json:"tag,omitempty"`
	// the total number of messages sent with this tag
	Sent int32 `json:"sent,omitempty"`
	// the total number of hard bounces by messages with this tag
	HardBounces int32 `json:"hard_bounces,omitempty"`
	// the total number of soft bounces by messages with this tag
	SoftBounces int32 `json:"soft_bounces,omitempty"`
	// the total number of rejected messages with this tag
	Rejects int32 `json:"rejects,omitempty"`
	// the total number of spam complaints received for messages with this tag
	Complaints int32 `json:"complaints,omitempty"`
	// the total number of unsubscribe requests received for messages with this tag
	Unsubs int32 `json:"unsubs,omitempty"`
	// the total number of times messages with this tag have been opened
	Opens int32 `json:"opens,omitempty"`
	// the total number of times tracked URLs in messages with this tag have been clicked
	Clicks int32 `json:"clicks,omitempty"`
	Stats *InlineResponse20059Stats `json:"stats,omitempty"`
}
