/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body75 struct {
	// a valid api key
	Key string `json:"key"`
	// the immutable name of a template that exists in the user's account
	TemplateName string `json:"template_name"`
	// an array of template content to render. Each item in the array should be a struct with two keys - name: the name of the content block to set the content for, and content: the actual content to put into the block
	TemplateContent []TemplatesrenderTemplateContent `json:"template_content"`
	// optional merge variables to use for injecting merge field content. If this is not provided, no merge fields will be replaced.
	MergeVars []TemplatesrenderMergeVars `json:"merge_vars,omitempty"`
}
