/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// information on an individual click
type MessagessearchClicksDetail struct {
	// the unix timestamp from when the message was clicked
	Ts int32 `json:"ts,omitempty"`
	// the URL that was clicked on
	Url string `json:"url,omitempty"`
	// the IP address that generated the click
	Ip string `json:"ip,omitempty"`
	// the approximate region and country that the clicking IP is located
	Location string `json:"location,omitempty"`
	// the email client or browser data of the click
	Ua string `json:"ua,omitempty"`
}
