/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

type Body14 struct {
	// a valid api key
	Key string `json:"key"`
	// an existing inbound domain
	Domain string `json:"domain"`
	// the search pattern that the mailbox name should match
	Pattern string `json:"pattern"`
	// the webhook URL where the inbound messages will be published
	Url string `json:"url"`
}
