/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

type TemplatesAddBody struct {
	// a valid api key
	Key string `json:"key"`
	// the name for the new template - must be unique
	Name string `json:"name"`
	// a default sending address for emails sent using this template
	FromEmail string `json:"from_email,omitempty"`
	// a default from name to be used
	FromName string `json:"from_name,omitempty"`
	// a default subject line to be used
	Subject string `json:"subject,omitempty"`
	// the HTML code for the template with mc:edit attributes for the editable elements
	Code string `json:"code,omitempty"`
	// a default text part to be used when sending with this template
	Text string `json:"text,omitempty"`
	// set to false to add a draft template without publishing
	Publish bool `json:"publish,omitempty"`
	// an optional array of up to 10 labels to use for filtering templates
	Labels []string `json:"labels,omitempty"`
}
