/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the information for the updated metadata field
type InlineResponse20038 struct {
	// the unique identifier of the metadata field to update
	Name string `json:"name,omitempty"`
	// the current state of the metadata field
	State string `json:"state,omitempty"`
	// Mustache template to control how the metadata is rendered in your activity log
	ViewTemplate string `json:"view_template,omitempty"`
}
