/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

type AllowlistsDeleteBody struct {
	// a valid api key
	Key string `json:"key"`
	// the email address to remove from the allowlist
	Email string `json:"email"`
}
