/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// information about the tracking domain
type InlineResponse20071 struct {
	// the tracking domain name
	Domain string `json:"domain,omitempty"`
	// the date and time that the tracking domain was added as a UTC string in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// when the domain's DNS settings were last tested as a UTC string in YYYY-MM-DD HH:MM:SS format
	LastTestedAt time.Time `json:"last_tested_at,omitempty"`
	Cname *UrlstrackingdomainsCname `json:"cname,omitempty"`
	// whether this domain can be used as a tracking domain for email.
	ValidTracking bool `json:"valid_tracking,omitempty"`
}
