/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// an aggregate summary of the sender's sending stats
type InlineResponse20048Stats struct {
	Today *InlineResponse20048StatsToday `json:"today,omitempty"`
	Last7Days *InlineResponse20048StatsLast7Days `json:"last_7_days,omitempty"`
	Last30Days *InlineResponse20048StatsLast30Days `json:"last_30_days,omitempty"`
	Last60Days *InlineResponse20048StatsLast60Days `json:"last_60_days,omitempty"`
	Last90Days *InlineResponse20048StatsLast90Days `json:"last_90_days,omitempty"`
}
