/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// tats for the lifetime of the user's account
type InlineResponse20072StatsAllTime struct {
	// the number of emails sent in the lifetime of the user's account
	Sent int32 `json:"sent,omitempty"`
	// the number of emails hard bounced in the lifetime of the user's account
	HardBounces int32 `json:"hard_bounces,omitempty"`
	// the number of emails soft bounced in the lifetime of the user's account
	SoftBounces int32 `json:"soft_bounces,omitempty"`
	// the number of emails rejected for sending this user so far today
	Rejects int32 `json:"rejects,omitempty"`
	// the number of spam complaints in the lifetime of the user's account
	Complaints int32 `json:"complaints,omitempty"`
	// the number of unsubscribes in the lifetime of the user's account
	Unsubs int32 `json:"unsubs,omitempty"`
	// the number of times emails have been opened in the lifetime of the user's account
	Opens int32 `json:"opens,omitempty"`
	// the number of unique opens for emails sent in the lifetime of the user's account
	UniqueOpens int32 `json:"unique_opens,omitempty"`
	// the number of URLs that have been clicked in the lifetime of the user's account
	Clicks int32 `json:"clicks,omitempty"`
	// the number of unique clicks for emails sent in the lifetime of the user's account
	UniqueClicks int32 `json:"unique_clicks,omitempty"`
}
