/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// information about the activity export job that was started
type InlineResponse2007 struct {
	// the unique identifier for this Export. Use this identifier when checking the export job's status
	Id string `json:"id,omitempty"`
	// the date and time that the export job was created as a UTC string in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the type of the export job
	Type_ string `json:"type,omitempty"`
	// the date and time that the export job was finished as a UTC string in YYYY-MM-DD HH:MM:SS format, or null for jobs that have not run
	FinishedAt time.Time `json:"finished_at,omitempty"`
	// the export job's state
	State string `json:"state,omitempty"`
	// the url for the export job's results, if the job is complete
	ResultUrl string `json:"result_url,omitempty"`
}
