/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// a struct with one key \"PING\" with a static value \"PONG!\"
type InlineResponse20073 struct {
	// a simple pong response
	PING string `json:"PING,omitempty"`
}
