/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// metadata for a single recipient
type MessagessendMessageRecipientMetadata struct {
	// the email address of the recipient that the metadata is associated with
	Rcpt string `json:"rcpt,omitempty"`
	Values *MessagessendMessageValues `json:"values,omitempty"`
}
