/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// the injection of a single piece of content into a single editable region
type MessagessendtemplateTemplateContent struct {
	// the name of the mc:edit editable region to inject into
	Name string `json:"name,omitempty"`
	// the content to inject
	Content string `json:"content,omitempty"`
}
