/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

type AllowlistsListBody struct {
	// a valid api key
	Key string `json:"key"`
	// an optional email address or prefix to search by
	Email string `json:"email,omitempty"`
}
