/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// information about the dedicated IP's new configuration
type InlineResponse20027 struct {
	// the ip address
	Ip string `json:"ip,omitempty"`
	// the date and time that the dedicated IP was created as a UTC string in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the name of the pool that this dedicated IP belongs to
	Pool string `json:"pool,omitempty"`
	// the domain name (reverse dns) of this dedicated IP
	Domain string `json:"domain,omitempty"`
	CustomDns *IpslistCustomDns `json:"custom_dns,omitempty"`
	Warmup *IpslistWarmup `json:"warmup,omitempty"`
}
