/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional

// a description of the ip that was removed from your account.
type InlineResponse20022 struct {
	// the ip address
	Ip string `json:"ip,omitempty"`
	// a boolean indicating whether the ip was successfully deleted
	Deleted string `json:"deleted,omitempty"`
}
