/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// information about the inbound domain
type InlineResponse20010 struct {
	// the domain name that is accepting mail
	Domain string `json:"domain,omitempty"`
	// the date and time that the inbound domain was added as a UTC string in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// true if this inbound domain has successfully set up an MX record to deliver mail to the Mandrill servers
	ValidMx bool `json:"valid_mx,omitempty"`
}
