/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

import (
	"time"
)

// the information for each rejection  entry
type InlineResponse20041 struct {
	// the email that is blocked
	Email string `json:"email,omitempty"`
	// the type of event (hard-bounce, soft-bounce, spam, unsub, custom) that caused this rejection
	Reason string `json:"reason,omitempty"`
	// extended details about the event, such as the SMTP diagnostic for bounces or the comment for manually-created rejections
	Detail string `json:"detail,omitempty"`
	// when the email was added to the denylist
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the timestamp of the most recent event that either created or renewed this rejection
	LastEventAt time.Time `json:"last_event_at,omitempty"`
	// when the denylist entry will expire (this may be in the past)
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// whether the denylist entry has expired
	Expired bool `json:"expired,omitempty"`
	Sender *RejectslistSender `json:"sender,omitempty"`
	// the subaccount that this denylist entry applies to, or null if none.
	Subaccount string `json:"subaccount,omitempty"`
}
