/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// the information for the paused subaccount
type InlineResponse20055 struct {
	// a unique indentifier for the subaccount
	Id string `json:"id,omitempty"`
	// an optional display name for the subaccount
	Name string `json:"name,omitempty"`
	// an optional manual hourly quota for the subaccount. If not specified, the hourly quota will be managed based on reputation
	CustomQuota int32 `json:"custom_quota,omitempty"`
	// the current sending status of the subaccount
	Status string `json:"status,omitempty"`
	// the subaccount's current reputation on a scale from 0 to 100
	Reputation int32 `json:"reputation,omitempty"`
	// the date and time that the subaccount was created as a UTC string in YYYY-MM-DD HH:MM:SS format
	CreatedAt time.Time `json:"created_at,omitempty"`
	// the date and time that the subaccount first sent as a UTC string in YYYY-MM-DD HH:MM:SS format
	FirstSentAt time.Time `json:"first_sent_at,omitempty"`
	// the number of emails the subaccount has sent so far this week (weeks start on midnight Monday, UTC)
	SentWeekly int32 `json:"sent_weekly,omitempty"`
	// the number of emails the subaccount has sent so far this month (months start on midnight of the 1st, UTC)
	SentMonthly int32 `json:"sent_monthly,omitempty"`
	// the number of emails the subaccount has sent since it was created
	SentTotal int32 `json:"sent_total,omitempty"`
}
