/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the sending results for a single recipient
type InlineResponse20029 struct {
	// the email address of the recipient
	Email string `json:"email,omitempty"`
	// the sending status of the recipient
	Status string `json:"status,omitempty"`
	// the reason for the rejection if the recipient status is \"rejected\"
	RejectReason string `json:"reject_reason,omitempty"`
	// the message's unique id
	Id string `json:"_id,omitempty"`
}
