/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package MailchimpTransactional

// the content of the message
type InlineResponse20033 struct {
	// the Unix timestamp from when this message was sent
	Ts int32 `json:"ts,omitempty"`
	// the message's unique id
	Id string `json:"_id,omitempty"`
	// the email address of the sender
	FromEmail string `json:"from_email,omitempty"`
	// the alias of the sender (if any)
	FromName string `json:"from_name,omitempty"`
	// the message's subject line
	Subject string `json:"subject,omitempty"`
	To *InlineResponse20033To `json:"to,omitempty"`
	// list of tags on this message
	Tags []string `json:"tags,omitempty"`
	// the key-value pairs of the custom MIME headers for the message's main document
	Headers *interface{} `json:"headers,omitempty"`
	// the text part of the message, if any
	Text string `json:"text,omitempty"`
	// the HTML part of the message, if any
	Html string `json:"html,omitempty"`
	// an array of any attachments that can be found in the message
	Attachments []InlineResponse20033Attachments `json:"attachments,omitempty"`
}
