/*
 * Mailchimp Transactional API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.47
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapitransactional
import (
	"time"
)

// information about the ip's warmup status
type IpslistWarmup struct {
	// whether the ip is currently in warmup mode
	WarmingUp bool `json:"warming_up,omitempty"`
	// the start time for the warmup process as a UTC string in YYYY-MM-DD HH:MM:SS format
	StartAt time.Time `json:"start_at,omitempty"`
	// the end date and time for the warmup process as a UTC string in YYYY-MM-DD HH:MM:SS format
	EndAt time.Time `json:"end_at,omitempty"`
}
